theme = "base16_transparent"

[editor]
end-of-line-diagnostics = "hint"
auto-format = false
auto-completion = true
line-number = "relative"
cursorline = false
continue-comments = false
completion-timeout = 5
bufferline = "always"
preview-completion-insert = false
completion-trigger-len = 2

[editor.word-completion]
enable = true
trigger-length = 2

[editor.lsp]
# display-inlay-hints = true
auto-signature-help = false

# [editor.auto-pairs]
# '{' = '}'
# '[' = ']'
# '(' = ')'

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
# space = "all"
# tab = "all"

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "╎" "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[keys.insert]
"A-x" = "normal_mode"
"C-s" = ":update"
"C-z" = "signature_help"
"C-space" = "completion"


[keys.normal]
"i" = ["collapse_selection", "insert_mode"]
"a" = "@li"
"X" = "select_line_above"
"A-x" = ":reset-diff-change"
"C-z" = "signature_help"
"C-b" = "@:run-shell-command bash build.sh build<ret>"
"C-r" = "@:run-shell-command bash build.sh run<ret>"
