[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
typstExtraArgs = ["main.typ"]
exportPdf = "onType"
outputPath = "$dir/$name"

[language-server.tinymist.config.preview]
background.enabled = true
background.args = [
  "--data-plane-host=127.0.0.1:0",
  "--invert-colors=never",
  "--open"
]

[[language]]
name = "typst"
language-servers = ["tinymist"]

# [[language]]
# name = "odin"
# indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "\t" }

# [[language]]
# name = "json"
# indent = { tab-width = 4, unit = "\t" }

# [[language]]
# name = "php"
# indent = { tab-width = 2, unit = "\t" }

[language-server.rust-analyzer.config.check]
command = "clippy"
features = "all"
